### ISSUE TITLE
Footer - Need Help icon missing at bottom right corner of footer

### ISSUE THREAD

**Issue by pearlson16** [SportsToken/ax_dapp#465]
https://athletex.atlassian.net/browse/AX-645

**Environment**
Device model: All
OS version: All
Software version: All
Browser version: All
Stage: All
Account: N/A

**Precondition**
Given, user has gone to the website

**Steps to reproduce**
Go to [AthleteX dApp](https://staging.athletex.io/#/)  
Scroll down to footer and you will see Need Help icon is missing compare to design

**Current behavior**
Currently, Need Help icon is missing at bottom right corner of footer

**Expected behavior**
Need Help with help text popup should appear as per design

<img width="1731" alt="Screenshot 2022-06-19 at 3 18 52 AM" src="https://user-images.githubusercontent.com/57809593/178850200-ad61d094-113a-4a70-9a3d-2604d4fc5913.png">

**Comment by ketonkss4** [comment]
@pearlson16 was this completed?
